-- =====================================================
-- Step 1: Account setup
-- Create roles, warehouse, database, and schema
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- Roles
CREATE ROLE IF NOT EXISTS DEMO_INTELLIGENCE_ADMIN;
CREATE ROLE IF NOT EXISTS DEMO_INTELLIGENCE_USER;

-- Role hierarchy
GRANT ROLE DEMO_INTELLIGENCE_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE DEMO_INTELLIGENCE_USER  TO ROLE DEMO_INTELLIGENCE_ADMIN;

-- Cortex AI permissions
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEMO_INTELLIGENCE_USER;

-- Git repository access
GRANT USAGE ON DATABASE   SNOWFLAKE_QUICKSTART_REPOS                        TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT USAGE ON SCHEMA     SNOWFLAKE_QUICKSTART_REPOS.GIT_REPOS               TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT READ  ON GIT REPOSITORY SNOWFLAKE_QUICKSTART_REPOS.GIT_REPOS.DEMO_REPO TO ROLE DEMO_INTELLIGENCE_ADMIN;

-- Warehouse
CREATE OR REPLACE WAREHOUSE DEMO_INTELLIGENCE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    COMMENT        = 'Snowflake Intelligence demo warehouse';

GRANT USAGE ON WAREHOUSE DEMO_INTELLIGENCE_WH TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT USAGE ON WAREHOUSE DEMO_INTELLIGENCE_WH TO ROLE DEMO_INTELLIGENCE_USER;

-- Switch session to the new warehouse immediately
-- (prevents "warehouse was dropped" error when re-running after teardown)
USE WAREHOUSE DEMO_INTELLIGENCE_WH;

-- Database: create first, then transfer ownership, then create schema under ADMIN role
CREATE OR REPLACE DATABASE DEMO_INTELLIGENCE_DB
    COMMENT = 'Snowflake Intelligence demo DB';

GRANT OWNERSHIP ON DATABASE DEMO_INTELLIGENCE_DB
    TO ROLE DEMO_INTELLIGENCE_ADMIN COPY CURRENT GRANTS;

-- Create schema under ADMIN role (avoids insufficient privileges on schema)
USE ROLE DEMO_INTELLIGENCE_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_INTELLIGENCE_DB.ANALYTICS;

-- Grant read access to USER role
USE ROLE ACCOUNTADMIN;
GRANT USAGE  ON DATABASE DEMO_INTELLIGENCE_DB                                TO ROLE DEMO_INTELLIGENCE_USER;
GRANT USAGE  ON SCHEMA   DEMO_INTELLIGENCE_DB.ANALYTICS                      TO ROLE DEMO_INTELLIGENCE_USER;
GRANT SELECT ON ALL TABLES    IN SCHEMA DEMO_INTELLIGENCE_DB.ANALYTICS TO ROLE DEMO_INTELLIGENCE_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_INTELLIGENCE_DB.ANALYTICS TO ROLE DEMO_INTELLIGENCE_USER;

SELECT '01_configure_account: done' AS status;
