-- =====================================================
-- Step 1: アカウント設定
-- ロール、ウェアハウス、データベース、スキーマを作成する
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- ロール作成
CREATE ROLE IF NOT EXISTS DEMO_INTELLIGENCE_ADMIN;
CREATE ROLE IF NOT EXISTS DEMO_INTELLIGENCE_USER;

-- ロール階層
GRANT ROLE DEMO_INTELLIGENCE_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE DEMO_INTELLIGENCE_USER  TO ROLE DEMO_INTELLIGENCE_ADMIN;

-- Cortex AI 権限を付与
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEMO_INTELLIGENCE_USER;

-- Git リポジトリへのアクセス権
GRANT USAGE ON DATABASE SNOWFLAKE_QUICKSTART_REPOS TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT USAGE ON SCHEMA  SNOWFLAKE_QUICKSTART_REPOS.GIT_REPOS TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT READ ON GIT REPOSITORY SNOWFLAKE_QUICKSTART_REPOS.GIT_REPOS.DEMO_REPO TO ROLE DEMO_INTELLIGENCE_ADMIN;

-- ウェアハウス作成
CREATE WAREHOUSE IF NOT EXISTS DEMO_INTELLIGENCE_WH
    WAREHOUSE_SIZE  = 'XSMALL'
    AUTO_SUSPEND    = 60
    AUTO_RESUME     = TRUE
    COMMENT         = 'Snowflake Intelligence デモ用ウェアハウス';

GRANT USAGE ON WAREHOUSE DEMO_INTELLIGENCE_WH TO ROLE DEMO_INTELLIGENCE_ADMIN;
GRANT USAGE ON WAREHOUSE DEMO_INTELLIGENCE_WH TO ROLE DEMO_INTELLIGENCE_USER;

-- データベースとスキーマ（CREATE OR REPLACE で冪等）
CREATE OR REPLACE DATABASE DEMO_INTELLIGENCE_DB
    COMMENT = 'Snowflake Intelligence デモ用DB — teardown で削除可能';
CREATE OR REPLACE SCHEMA DEMO_INTELLIGENCE_DB.ANALYTICS;

-- デモ用ロールへ権限付与
GRANT OWNERSHIP ON DATABASE DEMO_INTELLIGENCE_DB
    TO ROLE DEMO_INTELLIGENCE_ADMIN COPY CURRENT GRANTS;

GRANT USAGE  ON DATABASE DEMO_INTELLIGENCE_DB            TO ROLE DEMO_INTELLIGENCE_USER;
GRANT USAGE  ON SCHEMA   DEMO_INTELLIGENCE_DB.ANALYTICS  TO ROLE DEMO_INTELLIGENCE_USER;
GRANT SELECT ON ALL TABLES    IN SCHEMA DEMO_INTELLIGENCE_DB.ANALYTICS TO ROLE DEMO_INTELLIGENCE_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_INTELLIGENCE_DB.ANALYTICS TO ROLE DEMO_INTELLIGENCE_USER;

SELECT '01_configure_account: 完了' AS status;
